[
    "mehendi",
    "dark purple",
    "royal blue",
    "burnt maroon",
    "light peach",
    "ocean blue",
    "mustard yellow",
    "dark pink",
    "peach orange",
    "baby pink",
    "Dark Green",
    "Glossy Red",
    "Black",
    "White",
    "red",
    "Blue",
    "Green",
    "Yellow",
    "Pink",
]